### ISSUE TITLE
Different name

### ISSUE THREAD

**Issue by dtolnay** [bm371613/rr#1]
Just registering the concern from https://www.reddit.com/r/rust/comments/9p3295/rr_refactoringrenaming_tool_written_also_my_first/e7ypdq4/ (which I share).

> I'd caution against using that name in the software development space, as it's been in use for a number of years by a debugger from the Mozilla folks:
>
> - https://rr-project.org/
> - https://en.wikipedia.org/wiki/Rr_(debugging)
> - https://github.com/mozilla/rr

**Comment by bm371613** [comment]
I've just renamed `rr` to `refren` in code, I will soon rename this repository as well. Thanks for your help!
